
# spring.data.mongodb.uri=mongodb://localhost:27017/demo
# grpc.server.port=9090
# springdoc.api-docs.path=/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/demo
  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 9090

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spark:
  app-name: DemoSparkApplication
  master: local[*]
    